baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Hugo Tina Starter'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
[module]
[[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke'
[build.processing]
    skip_processing = true